#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [ ! -n "$VIRTUAL_ENV" ]; then
  if [ -x "$(command -v uv)" ]; then
    uv venv .venv
  else
    python3 -m venv .venv
  fi
  source .venv/bin/activate
fi

python3 -m pip install homeassistant
# This might fail if the file is missing, we dont care
python3 -m pip install --requirement requirements.txt